export const colorTokens = [
  "bg-border",
  "bg-input",
  "bg-ring",
  "bg-background",
  "bg-foreground",
  "bg-card",
  "bg-panel",
  "bg-card-hairline",
  "bg-primary",
  "bg-primary-foreground",
  "bg-primary-soft",
  "bg-accent",
  "bg-accent-soft",
  "bg-accent-2",
  "bg-glow",
  "bg-ring-muted",
  "bg-danger",
  "bg-warning",
  "bg-success",
  "bg-success-glow",
  "bg-aurora-g",
  "bg-aurora-g-light",
  "bg-aurora-p",
  "bg-aurora-p-light",
  "bg-muted",
  "bg-muted-foreground",
  "bg-lav-deep",
  "bg-surface-vhs",
  "bg-surface-streak",
  "bg-card-foreground",
  "bg-accent-foreground",
  "bg-destructive",
  "bg-destructive-foreground",
  "bg-button-primary-surface",
  "bg-button-primary-hover",
  "bg-button-primary-border",
];

export const spacingTokens = [4, 8, 12, 16, 24, 32, 48, 64];

export const radiusTokens = [
  "--radius-md",
  "--radius-lg",
  "--radius-xl",
  "--radius-2xl",
];
