name: Setup Node project
description: Prepare a Node.js environment with pnpm and install dependencies.

inputs:
  node-version:
    description: Node.js version to install.
    required: false
    default: '22.x'
  pnpm-version:
    description: pnpm version to activate via Corepack.
    required: false
    default: '9.12.3'
  working-directory:
    description: Directory that contains the project to install.
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        cache-dependency-path: ${{ inputs.working-directory }}/pnpm-lock.yaml

    - name: Enable Corepack and pnpm
      shell: bash
      run: |
        set -euo pipefail
        corepack enable
        corepack use pnpm@${{ inputs.pnpm-version }}

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -euo pipefail
        pnpm install --frozen-lockfile --prefer-offline --ignore-scripts=false

    - name: Verify versions
      shell: bash
      run: |
        set -euo pipefail
        node -v
        pnpm -v
