// Auto-generated by scripts/build-gallery-usage.ts
// Stubbed manifest used in tests; run `pnpm run build-gallery-usage` to regenerate.

import type {
  GalleryPreviewRoute,
  GalleryRegistryPayload,
  GallerySection,
} from './registry'

export interface GalleryModuleExport {
  readonly default: GallerySection | readonly GallerySection[]
}

export interface GalleryPreviewModuleManifest {
  readonly loader: () => Promise<GalleryModuleExport>
  readonly previewIds: readonly string[]
}

export const galleryPayload: GalleryRegistryPayload = {
  sections: [],
  byKind: {
    primitive: [],
    component: [],
    complex: [],
    token: [],
  },
}

export const galleryPreviewRoutes: readonly GalleryPreviewRoute[] = []

export const galleryPreviewModules: Record<
  string,
  GalleryPreviewModuleManifest
> = Object.freeze({})

