name: Deploy Pages

concurrency:
  group: deploy-pages-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - work
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - 'CHANGELOG.md'
  workflow_dispatch:

permissions:
  contents: read
  actions: write
  pages: write

jobs:
  build:
    name: Build static site
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    env:
      NEXT_TELEMETRY_DISABLED: '1'
      BASE_PATH: Planner
      NEXT_PUBLIC_BASE_PATH: /Planner
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.2.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - uses: ./.github/actions/setup-node-project
        with:
          checkout-ref: ${{ github.event.pull_request.head.sha || github.sha }}
          checkout-fetch-depth: 0
          cache-suffix: ${{ vars.NODE_MODULES_CACHE_BUSTER }}
          skip-checkout: 'true'

      - name: Verify prompts registry
        run: pnpm run verify-prompts

      - name: Validate env for deploy
        shell: bash
        run: |
          set -euo pipefail
          pnpm exec tsx scripts/validate-deploy-env.ts

      - name: Build and publish static site
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          pnpm run deploy
