name: Deploy Pages

concurrency:
  group: deploy-pages-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - work
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - 'CHANGELOG.md'
  workflow_dispatch:

permissions:
  contents: read
  actions: write
  pages: write

jobs:
  build:
    name: Build static site
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    env:
      NEXT_TELEMETRY_DISABLED: '1'
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-node-project
        with:
          checkout-ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Verify prompts registry
        run: pnpm run verify-prompts

      - name: Export static site
        shell: bash
        run: |
          set -euo pipefail
          export DEPLOY_ARTIFACT_ONLY=true
          # The deploy script derives the correct base path for project pages and
          # clears it for user/org pages, so no extra env wiring is required here.
          pnpm run deploy

      - name: Upload static artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: ./out

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    if: needs.build.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: Production
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@af48c8d784fbb3eccd0f19f41da3b3c25c2ba234 # v4.0.7
