name: Deploy Pages

concurrency:
  group: deploy-pages-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - 'CHANGELOG.md'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    name: Build static site
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    env:
      NEXT_TELEMETRY_DISABLED: '1'
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4.2.1
        with:
          fetch-depth: 2
          ref: ${{ github.ref }}

      - uses: ./.github/actions/setup-node-project

      - name: Verify prompts registry
        run: npm run verify-prompts

      - name: Export static site
        shell: bash
        run: |
          set -euo pipefail
          export DEPLOY_ARTIFACT_ONLY=true
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          if [[ "${REPO_NAME}" == *.github.io ]]; then
            export NEXT_PUBLIC_BASE_PATH=""
          else
            export NEXT_PUBLIC_BASE_PATH="/${REPO_NAME}"
          fi
          npm run deploy

      - name: Upload static artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: ./out

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    if: needs.build.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: Production
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@af48c8d784fbb3eccd0f19f41da3b3c25c2ba234 # v4.0.7
