name: Deploy Preview

concurrency:
  group: ${{ github.event_name == 'pull_request' && format('deploy-preview-{0}', github.event.pull_request.number) || format('deploy-preview-{0}', github.ref) }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - 'CHANGELOG.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build static preview
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      NEXT_TELEMETRY_DISABLED: '1'
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.2.1
        with:
          fetch-depth: 0
          # Use the head SHA for PRs; fall back to the workflow ref for other events.
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.ref }}

      - uses: ./.github/actions/setup-node-project

      - name: Verify prompts registry
        run: npm run verify-prompts

      - name: Export static preview
        shell: bash
        run: |
          set -euo pipefail
          export DEPLOY_ARTIFACT_ONLY=true
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          if [[ "${REPO_NAME}" == *.github.io ]]; then
            export NEXT_PUBLIC_BASE_PATH=""
          else
            export NEXT_PUBLIC_BASE_PATH="/${REPO_NAME}"
          fi
          npm run deploy

      - name: Upload static artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: ./out
          if-no-files-found: error

  deploy:
    name: Deploy preview
    needs: build
    if: needs.build.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: Deploy Preview
      url: ${{ steps.deploy.outputs.page_url }}
    outputs:
      page_url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@f65c7f0a20510b02fd348436de4b0bd711c4d7f9 # v5.0.1

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@af48c8d784fbb3eccd0f19f41da3b3c25c2ba234 # v4.0.7
        with:
          preview: true

  share:
    name: Share preview URL
    needs: deploy
    if: github.event_name == 'pull_request' && needs.deploy.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Post preview comment
        uses: actions/github-script@d59a4d062958ca40b034b6f04da4898e95a1c18f # v7.0.1
        with:
          script: |
            const marker = '<!-- preview-link -->';
            const url = process.env.PREVIEW_URL || '';
            if (!url) {
              core.warning('Preview URL missing; skipping comment update.');
              return;
            }
            const body = `${marker}\nPreview ready: ${url}`;
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              per_page: 100,
            });
            const existing = comments.find((comment) => comment.user?.type === 'Bot' && comment.body.includes(marker));
            if (existing) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existing.id,
                body,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body,
              });
            }
        env:
          PREVIEW_URL: ${{ needs.deploy.outputs.page_url }}
