name: Workflow Lint

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
      - '.yamllint.yaml'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
      - '.yamllint.yaml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Run actionlint
        uses: rhysd/actionlint@v1
      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          python -m pip install yamllint
      - name: Run yamllint
        run: yamllint .github/workflows
