name: Workflow Lint

concurrency:
  group: workflow-lint-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
      - work
    paths:
      - '.github/**/*.yml'
      - '.github/**/*.yaml'
  push:
    branches:
      - main
      - work
    paths:
      - '.github/**/*.yml'
      - '.github/**/*.yaml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # Runs actionlint and yamllint to keep GitHub workflow definitions valid and stylistically consistent.
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v4.2.1
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup Node project
        uses: ./.github/actions/setup-node-project
        with:
          cache-suffix: ${{ vars.NODE_MODULES_CACHE_BUSTER }}
          skip-checkout: 'true'

      - name: Run actionlint across workflows
        uses: reviewdog/action-actionlint@0b71b30a47a15c4d849868cca394fb656f1cf657 # v1.67.0
        with:
          github_token: ${{ github.token }}
          fail_level: error
          filter_mode: nofilter
          actionlint_flags: --color never

      - name: Install yamllint
        run: sudo apt-get update && sudo apt-get install -y yamllint

      - name: Run yamllint
        run: |
          yamllint -d "{extends: default, rules: {line-length: {max: 200}, comments: disable, document-start: disable, truthy: disable}}" .github

      - name: Guard transient artifacts
        if: always()
        run: pnpm run guard:artifacts
