name: "Verify tool versions"
description: "Ensure Node.js and pnpm versions match repository expectations."

inputs:
  node-version-file:
    description: "Path to the Node.js version file"
    default: ".nvmrc"
  pnpm-version:
    description: "Expected pnpm version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check Node.js and pnpm versions
      shell: bash
      env:
        NODE_VERSION_FILE: "${{ inputs['node-version-file'] }}"
        EXPECTED_PNPM: "${{ inputs['pnpm-version'] }}"
      run: |
        set -euo pipefail

        if [ -z "$EXPECTED_PNPM" ]; then
          echo "Expected pnpm version must be provided." >&2
          exit 1
        fi

        if [ ! -f "$NODE_VERSION_FILE" ]; then
          echo "Node.js version file '$NODE_VERSION_FILE' not found." >&2
          exit 1
        fi

        EXPECTED_NODE_RAW="$(cat "$NODE_VERSION_FILE")"
        EXPECTED_NODE="$(echo "$EXPECTED_NODE_RAW" | tr -d '\n\r[:space:]')"
        EXPECTED_NODE="${EXPECTED_NODE#v}"

        if [ -z "$EXPECTED_NODE" ]; then
          echo "Node.js version file '$NODE_VERSION_FILE' did not contain a version." >&2
          exit 1
        fi

        ACTUAL_NODE_RAW="$(node --version)"
        ACTUAL_NODE="${ACTUAL_NODE_RAW#v}"

        if [[ "$EXPECTED_NODE" == *.* || "$EXPECTED_NODE" == *-* ]]; then
          if [ "$ACTUAL_NODE" != "$EXPECTED_NODE" ]; then
            echo "Node.js version mismatch. Expected $EXPECTED_NODE but found $ACTUAL_NODE." >&2
            exit 1
          fi
        else
          ACTUAL_NODE_MAJOR="${ACTUAL_NODE%%.*}"
          if [ "$ACTUAL_NODE_MAJOR" != "$EXPECTED_NODE" ]; then
            echo "Node.js major version mismatch. Expected $EXPECTED_NODE.x but found $ACTUAL_NODE." >&2
            exit 1
          fi
        fi

        ACTUAL_PNPM="$(pnpm --version)"

        if [ "$ACTUAL_PNPM" != "$EXPECTED_PNPM" ]; then
          echo "pnpm version mismatch. Expected $EXPECTED_PNPM but found $ACTUAL_PNPM." >&2
          exit 1
        fi

        echo "Using Node.js $ACTUAL_NODE_RAW and pnpm $ACTUAL_PNPM."
